# permissions for end users to view hellooperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hellooperator-viewer-role
rules:
- apiGroups:
  - webapp.io.github.kezhenxu94
  resources:
  - hellooperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.io.github.kezhenxu94
  resources:
  - hellooperators/status
  verbs:
  - get
